# Generated by Django 2.1.3 on 2018-12-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.IntegerField(default=1)),
                ('flag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='', max_length=200)),
                ('Last_Name', models.CharField(default='', max_length=200)),
                ('DOB', models.CharField(default='', max_length=200)),
                ('Loc', models.CharField(default='', max_length=200)),
                ('Email', models.CharField(default='', max_length=250)),
                ('Password', models.CharField(default='', max_length=250)),
                ('Gender', models.CharField(default='', max_length=250)),
                ('profile_picture', models.CharField(default='', max_length=250)),
                ('flag', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.User'),
        ),
    ]
