# Generated by Django 2.1.3 on 2018-12-08 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='flag',
            new_name='active',
        ),
    ]
