# Generated by Django 2.1.3 on 2018-12-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signup', '0002_auto_20181208_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='First_Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='Loc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
